WIDTH = 800
HEIGHT = 800
FPS = 30

BACKGROUND_COLOR = 'skyblue'
CLOUD_COLOR = 'white'
PLAYER_COLOR = 'yellow'
SCORE_COLOR = 'black'

PLAYER_SIZE = 60
CLOUD_GAP = 240
CLOUD_LENGTH = 30

MAX_CLOUD_SPEED = 25
MAX_PLAYER_SPEED = 50
ACCELERATION = 2

TIME_REWARD = 0.1
REWARD = 5
PUNISHMENT = -1

MAX_GENERATIONS = 100
